# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mrhea-ro <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/06 17:25:40 by mrhea-ro          #+#    #+#              #
#    Updated: 2018/12/06 19:25:59 by mrhea-ro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ./ft_display_file.c

all:
		gcc -Werror -Wall -Wextra $(SRCS) -o $(NAME)
clean:

fclean: clean
	rm -f $(NAME)
re: fclean all
